/**
 * API Documentation
 * The API description
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"

namespace OpenAPI
{

/*
 * OpenAPIPlayPositionLogDto
 *
 * 
 */
class OPENAPI_API OpenAPIPlayPositionLogDto : public Model
{
public:
    virtual ~OpenAPIPlayPositionLogDto() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	/* Player identifier */
	double Player;
	double X;
	double Y;
	TOptional<double> Z;
	int32 OffsetTimestamp = 0;
	TOptional<FString> Location;
};

}
