/**
 * API Documentation
 * The API description
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"
#include "OpenAPIHeatMapTaskResultListItem.h"
#include "OpenAPIPlaySessionResponseDto.h"
#include "OpenAPIProjectResponseDto.h"

namespace OpenAPI
{

/*
 * OpenAPIHeatmapTaskDto
 *
 * 
 */
class OPENAPI_API OpenAPIHeatmapTaskDto : public Model
{
public:
    virtual ~OpenAPIHeatmapTaskDto() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	/* Task ID */
	double TaskId;
	/* Project */
	OpenAPIProjectResponseDto Project;
	/* Session */
	TOptional<OpenAPIPlaySessionResponseDto> Session;
	/* Step size */
	double StepSize;
	/* Z visible */
	bool ZVisible = false;
	enum class StatusEnum
	{
		Pending,
		Processing,
		Completed,
		Failed,
		UnknownDefaultOpenApi,
  	};

	static FString EnumToString(const StatusEnum& EnumValue);
	static bool EnumFromString(const FString& EnumAsString, StatusEnum& EnumValue);
	/* Status */
	StatusEnum Status;
	/* Result list */
	TOptional<TArray<OpenAPIHeatMapTaskResultListItem>> Result;
	/* Created at */
	FDateTime CreatedAt;
	/* Updated at */
	FDateTime UpdatedAt;
};

}
