/**
 * API Documentation
 * The API description
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"

namespace OpenAPI
{

/*
 * OpenAPICalcNumberFieldDto
 *
 * 
 */
class OPENAPI_API OpenAPICalcNumberFieldDto : public Model
{
public:
    virtual ~OpenAPICalcNumberFieldDto() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	double Min;
	double Max;
	double Avg;
};

}
