/**
 * API Documentation
 * The API description
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "CoreMinimal.h"
#include "OpenAPIBaseModel.h"

namespace OpenAPI
{

class OPENAPI_API OpenAPIDefaultApi
{
public:
	OpenAPIDefaultApi();
	~OpenAPIDefaultApi();

	/* Sets the URL Endpoint.
	* Note: several fallback endpoints can be configured in request retry policies, see Request::SetShouldRetry */
	void SetURL(const FString& Url);

	/* Adds global header params to all requests */
	void AddHeaderParam(const FString& Key, const FString& Value);
	void ClearHeaderParams();

	/* Sets the retry manager to the user-defined retry manager. User must manage the lifetime of the retry manager.
	* If no retry manager is specified and a request needs retries, a default retry manager will be used.
	* See also: Request::SetShouldRetry */
	void SetHttpRetryManager(FHttpRetrySystem::FManager& RetryManager);
	FHttpRetrySystem::FManager& GetHttpRetryManager();

	class AppControllerGetHelloRequest;
	class AppControllerGetHelloResponse;
	class AppControllerGetRobotsRequest;
	class AppControllerGetRobotsResponse;
	
    DECLARE_DELEGATE_OneParam(FAppControllerGetHelloDelegate, const AppControllerGetHelloResponse&);
    DECLARE_DELEGATE_OneParam(FAppControllerGetRobotsDelegate, const AppControllerGetRobotsResponse&);
    
    FHttpRequestPtr AppControllerGetHello(const AppControllerGetHelloRequest& Request, const FAppControllerGetHelloDelegate& Delegate = FAppControllerGetHelloDelegate()) const;
    FHttpRequestPtr AppControllerGetRobots(const AppControllerGetRobotsRequest& Request, const FAppControllerGetRobotsDelegate& Delegate = FAppControllerGetRobotsDelegate()) const;
    
private:
    void OnAppControllerGetHelloResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FAppControllerGetHelloDelegate Delegate) const;
    void OnAppControllerGetRobotsResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FAppControllerGetRobotsDelegate Delegate) const;
    
	FHttpRequestRef CreateHttpRequest(const Request& Request) const;
	bool IsValid() const;
	void HandleResponse(FHttpResponsePtr HttpResponse, bool bSucceeded, Response& InOutResponse) const;

	FString Url;
	TMap<FString,FString> AdditionalHeaderParams;
	mutable FHttpRetrySystem::FManager* RetryManager = nullptr;
	mutable TUniquePtr<HttpRetryManager> DefaultRetryManager;
};

}
