/**
 * API Documentation
 * The API description
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"

namespace OpenAPI
{

/*
 * OpenAPIPlaySessionResponseDto
 *
 * 
 */
class OPENAPI_API OpenAPIPlaySessionResponseDto : public Model
{
public:
    virtual ~OpenAPIPlaySessionResponseDto() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	double SessionId;
	double ProjectId;
	FString Name;
	TOptional<FString> DeviceId;
	TOptional<FString> Platform;
	TOptional<FString> AppVersion;
	TOptional<TSharedPtr<FJsonObject>> MetaData;
	FDateTime StartTime;
	TOptional<FDateTime> EndTime;
	bool IsPlaying = false;
};

}
