/**
 * API Documentation
 * The API description
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"
#include "OpenAPIDefaultApi.h"

#include "OpenAPIDefaultErrorResponse.h"

namespace OpenAPI
{

/* 

*/
class OPENAPI_API OpenAPIDefaultApi::AppControllerGetHelloRequest : public Request
{
public:
    virtual ~AppControllerGetHelloRequest() {}
	void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
	FString ComputePath() const final;

};

class OPENAPI_API OpenAPIDefaultApi::AppControllerGetHelloResponse : public Response
{
public:
    virtual ~AppControllerGetHelloResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    
};

/* 

*/
class OPENAPI_API OpenAPIDefaultApi::AppControllerGetRobotsRequest : public Request
{
public:
    virtual ~AppControllerGetRobotsRequest() {}
	void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
	FString ComputePath() const final;

};

class OPENAPI_API OpenAPIDefaultApi::AppControllerGetRobotsResponse : public Response
{
public:
    virtual ~AppControllerGetRobotsResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    
};

}
