/**
 * API Documentation
 * The API description
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"

namespace OpenAPI
{

/*
 * OpenAPICreateHeatmapDto
 *
 * 
 */
class OPENAPI_API OpenAPICreateHeatmapDto : public Model
{
public:
    virtual ~OpenAPICreateHeatmapDto() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	/* Heatmap width */
	TOptional<double> StepSize;
	/* Whether to display the Z-axis */
	TOptional<bool> ZVisible;
};

}
