/**
 * API Documentation
 * The API description
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"

namespace OpenAPI
{

/*
 * OpenAPIHeatMapTaskResultListItem
 *
 * 
 */
class OPENAPI_API OpenAPIHeatMapTaskResultListItem : public Model
{
public:
    virtual ~OpenAPIHeatMapTaskResultListItem() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	/* X */
	double X;
	/* Y */
	double Y;
	/* Z */
	TOptional<double> Z;
	/* Density */
	double Density;
};

}
