/**
 * API Documentation
 * The API description
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "OpenAPICalcNumberFieldDto.h"

#include "OpenAPIModule.h"
#include "OpenAPIHelpers.h"

#include "Templates/SharedPointer.h"

namespace OpenAPI
{

void OpenAPICalcNumberFieldDto::WriteJson(JsonWriter& Writer) const
{
	Writer->WriteObjectStart();
	Writer->WriteIdentifierPrefix(TEXT("min")); WriteJsonValue(Writer, Min);
	Writer->WriteIdentifierPrefix(TEXT("max")); WriteJsonValue(Writer, Max);
	Writer->WriteIdentifierPrefix(TEXT("avg")); WriteJsonValue(Writer, Avg);
	Writer->WriteObjectEnd();
}

bool OpenAPICalcNumberFieldDto::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	const TSharedPtr<FJsonObject>* Object;
	if (!JsonValue->TryGetObject(Object))
		return false;

	bool ParseSuccess = true;

	ParseSuccess &= TryGetJsonValue(*Object, TEXT("min"), Min);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("max"), Max);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("avg"), Avg);

	return ParseSuccess;
}

}
