/**
 * API Documentation
 * The API description
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "OpenAPIPlayPositionLogDto.h"

#include "OpenAPIModule.h"
#include "OpenAPIHelpers.h"

#include "Templates/SharedPointer.h"

namespace OpenAPI
{

void OpenAPIPlayPositionLogDto::WriteJson(JsonWriter& Writer) const
{
	Writer->WriteObjectStart();
	Writer->WriteIdentifierPrefix(TEXT("player")); WriteJsonValue(Writer, Player);
	Writer->WriteIdentifierPrefix(TEXT("x")); WriteJsonValue(Writer, X);
	Writer->WriteIdentifierPrefix(TEXT("y")); WriteJsonValue(Writer, Y);
	if (Z.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("z")); WriteJsonValue(Writer, Z.GetValue());
	}
	Writer->WriteIdentifierPrefix(TEXT("offset_timestamp")); WriteJsonValue(Writer, OffsetTimestamp);
	if (Location.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("location")); WriteJsonValue(Writer, Location.GetValue());
	}
	Writer->WriteObjectEnd();
}

bool OpenAPIPlayPositionLogDto::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	const TSharedPtr<FJsonObject>* Object;
	if (!JsonValue->TryGetObject(Object))
		return false;

	bool ParseSuccess = true;

	ParseSuccess &= TryGetJsonValue(*Object, TEXT("player"), Player);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("x"), X);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("y"), Y);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("z"), Z);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("offset_timestamp"), OffsetTimestamp);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("location"), Location);

	return ParseSuccess;
}

}
