/**
 * API Documentation
 * The API description
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "OpenAPICreateHeatmapDto.h"

#include "OpenAPIModule.h"
#include "OpenAPIHelpers.h"

#include "Templates/SharedPointer.h"

namespace OpenAPI
{

void OpenAPICreateHeatmapDto::WriteJson(JsonWriter& Writer) const
{
	Writer->WriteObjectStart();
	if (StepSize.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("stepSize")); WriteJsonValue(Writer, StepSize.GetValue());
	}
	if (ZVisible.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("zVisible")); WriteJsonValue(Writer, ZVisible.GetValue());
	}
	Writer->WriteObjectEnd();
}

bool OpenAPICreateHeatmapDto::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	const TSharedPtr<FJsonObject>* Object;
	if (!JsonValue->TryGetObject(Object))
		return false;

	bool ParseSuccess = true;

	ParseSuccess &= TryGetJsonValue(*Object, TEXT("stepSize"), StepSize);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("zVisible"), ZVisible);

	return ParseSuccess;
}

}
